import { FormEvent, useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api, Artifact, Case, Extraction, NLQueryResponse } from "../api/client";

const QUERY_TEMPLATES = ["Show chat records containing crypto addresses", "List all communications with foreign numbers", "Show all WhatsApp messages", "List all call logs", "Find contacts with email addresses"];
type Tab = "ingest" | "search" | "investigate";

export default function CaseDetailPage() {
  const { caseId } = useParams<{ caseId: string }>();
  const [caseData, setCaseData] = useState<Case | null>(null);
  const [extractions, setExtractions] = useState<Extraction[]>([]);
  const [file, setFile] = useState<File | null>(null); const [password, setPassword] = useState("");
  const [searchQuery, setSearchQuery] = useState(""); const [nlQuery, setNlQuery] = useState("");
  const [searchResults, setSearchResults] = useState<Artifact[]>([]); const [nlResponse, setNlResponse] = useState<NLQueryResponse | null>(null);
  const [error, setError] = useState<string | null>(null); const [activeTab, setActiveTab] = useState<Tab>("ingest");
  const [uploading, setUploading] = useState(false); const [searching, setSearching] = useState(false); const [querying, setQuerying] = useState(false);

  const load = useCallback(() => { if (!caseId) return; api.getCase(caseId).then(setCaseData).catch((e) => setError(e.message)); api.listExtractions(caseId).then(setExtractions).catch((e) => setError(e.message)); }, [caseId]);
  useEffect(() => { load(); const timer = setInterval(load, 3000); return () => clearInterval(timer); }, [load]);
  const onUpload = async (e: FormEvent) => { e.preventDefault(); if (!caseId || !file) return; setError(null); setUploading(true); try { await api.uploadUfdr(caseId, file, password || undefined); setFile(null); setPassword(""); load(); } catch (err) { setError(err instanceof Error ? err.message : "Upload failed"); } finally { setUploading(false); } };
  const onSearch = async (e: FormEvent) => { e.preventDefault(); if (!caseId) return; setError(null); setSearching(true); try { setSearchResults(await api.search(caseId, { query: searchQuery || undefined })); } catch (err) { setError(err instanceof Error ? err.message : "Search failed"); } finally { setSearching(false); } };
  const onNlQuery = async (query: string) => { if (!caseId || !query.trim()) return; setNlQuery(query); setError(null); setQuerying(true); try { setNlResponse(await api.nlQuery(caseId, query)); setActiveTab("investigate"); } catch (err) { setError(err instanceof Error ? err.message : "Query failed"); } finally { setQuerying(false); } };
  const onExport = async () => { if (!caseId || !nlResponse) return; const text = await api.exportReport(caseId, nlResponse.query); const url = URL.createObjectURL(new Blob([text], { type: "text/plain" })); const a = document.createElement("a"); a.href = url; a.download = `ufdr-report-${caseData?.case_number || caseId}.txt`; a.click(); URL.revokeObjectURL(url); };
  if (!caseId) return null;
  const completed = extractions.filter((e) => e.status === "completed").length;
  return <>
    <Link to="/" className="back-link">← All investigation cases</Link>
    <section className="case-hero"><div><p className="eyebrow">Case workspace</p><h1>{caseData ? `${caseData.case_number}: ${caseData.title}` : "Loading case…"}</h1><p>{caseData?.description || "Review extraction progress and investigate device evidence."}</p></div><div className="case-meta"><div><span>Examinations</span><strong>{extractions.length}</strong></div><div><span>Ready</span><strong>{completed}</strong></div></div></section>
    <section className="workspace-tabs" aria-label="Case tools">{([ ["ingest", "01", "Ingest UFDR"], ["search", "02", "Evidence search"], ["investigate", "03", "AI investigation"] ] as const).map(([tab, num, label]) => <button type="button" key={tab} className={activeTab === tab ? "active" : ""} onClick={() => setActiveTab(tab)}><span>{num}</span>{label}</button>)}</section>
    {error && <div className="alert error"><strong>Action needs attention.</strong> {error}</div>}
    {activeTab === "ingest" && <section className="detail-layout"><div className="panel ingest-panel"><div className="panel-title"><div><p className="eyebrow">Evidence intake</p><h2>Add UFDR report</h2></div><p>Upload an exported Cellebrite UFDR archive.</p></div><form onSubmit={onUpload}><label className={file ? "file-drop selected" : "file-drop"}><input type="file" accept=".ufdr" onChange={(e) => setFile(e.target.files?.[0] || null)} /><span className="upload-icon">↑</span><strong>{file ? file.name : "Choose a UFDR file"}</strong><small>{file ? `${Math.max(1, Math.round(file.size / 1024 / 1024))} MB selected` : "Drop a .ufdr archive here or browse your device"}</small></label><div className="form-row compact"><label htmlFor="password">Archive password <span>optional</span></label><input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Required only for encrypted files" /></div><button type="submit" className="btn" disabled={!file || uploading}>{uploading ? "Uploading evidence…" : "Upload and ingest"}</button></form></div><aside className="panel guidance-panel"><p className="eyebrow">Intake protocol</p><h3>Preserve source integrity</h3><ol><li>Upload the original UFDR export.</li><li>Provide a password only when encrypted.</li><li>Wait for the extraction to complete before searching.</li></ol><small>All findings should be verified against the original report.</small></aside></section>}
    {activeTab === "ingest" && <section className="panel extraction-panel"><div className="panel-toolbar"><div><p className="eyebrow">Evidence register</p><h2>UFDR extractions <span className="count-pill">{extractions.length}</span></h2></div></div>{extractions.length === 0 ? <div className="empty-state compact-empty"><span>▣</span><h3>No evidence uploaded</h3><p>Your UFDR reports will appear here with their processing status.</p></div> : <div className="extraction-list">{extractions.map((ex) => <ExtractionCard key={ex.id} extraction={ex} />)}</div>}</section>}
    {activeTab === "search" && <section className="panel investigation-panel"><div className="panel-title"><div><p className="eyebrow">Direct evidence retrieval</p><h2>Search artifacts</h2></div><p>Search across ingested chats, calls, contacts, and locations.</p></div><form className="query-form" onSubmit={onSearch}><input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search names, phone numbers, messages, URLs…" /><button type="submit" className="btn" disabled={searching}>{searching ? "Searching…" : "Search evidence"}</button></form><ArtifactResults results={searchResults} searched={searching || Boolean(searchQuery)} /></section>}
    {activeTab === "investigate" && <section className="panel investigation-panel"><div className="panel-title"><div><p className="eyebrow">AI-assisted review</p><h2>Investigate evidence</h2></div><p>Answers are linked to underlying artifacts for verification.</p></div><div className="query-templates">{QUERY_TEMPLATES.map((q) => <button key={q} type="button" onClick={() => onNlQuery(q)}>{q}</button>)}</div><form className="query-form" onSubmit={(e) => { e.preventDefault(); onNlQuery(nlQuery); }}><input value={nlQuery} onChange={(e) => setNlQuery(e.target.value)} placeholder="Ask a question about this case…" /><button type="submit" className="btn" disabled={querying}>{querying ? "Analyzing…" : "Run investigation"}</button></form>{nlResponse ? <><div className="finding"><div><p className="eyebrow">Investigation finding</p><h3>{nlResponse.result_count} cited {nlResponse.result_count === 1 ? "result" : "results"}</h3></div><span className="intent-label">{nlResponse.intent}</span><p>{nlResponse.summary}</p>{nlResponse.result_count > 0 && <button type="button" className="btn secondary" onClick={onExport}>Export cited report</button>}</div><CitationResults citations={nlResponse.citations} /></> : <div className="empty-state compact-empty"><span>✦</span><h3>Ask the evidence</h3><p>Choose a prompt above or enter a natural-language investigation question.</p></div>}</section>}
  </>;
}

function ExtractionCard({ extraction: ex }: { extraction: Extraction }) { const device = ex.device_info && Object.entries(ex.device_info).slice(0, 2); return <article className="extraction-card"><div className="extraction-icon">▣</div><div className="extraction-main"><div className="extraction-heading"><strong>{ex.filename}</strong><span className={`status ${ex.status}`}>{ex.status}</span></div><p>{device?.length ? device.map(([k, v]) => `${k}: ${v}`).join(" · ") : "UFDR evidence archive"}</p>{ex.status === "processing" && <div className="progress-row"><div className="progress-bar"><div style={{ width: `${ex.progress}%` }} /></div><span>{ex.progress}% processed</span></div>}{ex.stats && <div className="stat-line">{Object.entries(ex.stats).map(([k, v]) => <span key={k}>{v} {k}</span>)}</div>}{ex.error_message && <p className="error-text">{ex.error_message}</p>}</div><time>{ex.completed_at ? "Completed" : "Added"}<br />{new Date(ex.created_at).toLocaleDateString()}</time></article>; }
function ArtifactResults({ results, searched }: { results: Artifact[]; searched: boolean }) { if (!results.length) return <div className="empty-state compact-empty"><span>⌕</span><h3>{searched ? "No evidence matches yet" : "Start with an evidence search"}</h3><p>{searched ? "Try a more specific name, term, number, or application." : "Results will be displayed here with their source context."}</p></div>; return <div className="result-list">{results.map((a) => <EvidenceCard key={a.id} type={a.artifact_type} title={a.title} app={a.app_name} timestamp={a.timestamp} text={a.content || ""} entities={a.entities} />)}</div>; }
function CitationResults({ citations }: { citations: NLQueryResponse["citations"] }) { if (!citations.length) return <div className="empty-state compact-empty"><span>⌕</span><h3>No cited evidence found</h3><p>Refine the question or search the extracted artifacts directly.</p></div>; return <div className="result-list">{citations.map((c) => <EvidenceCard key={c.artifact_id} type={c.artifact_type} title={c.title} app={c.app_name} timestamp={c.timestamp} text={c.excerpt} entities={c.entities} citationId={c.artifact_id} />)}</div>; }
function EvidenceCard({ type, title, app, timestamp, text, entities, citationId }: { type: string; title: string | null; app: string | null; timestamp: string | null; text: string; entities: { entity_type: string; value: string }[]; citationId?: string }) { return <article className="evidence-card"><header><div><span className="artifact-type">{type}</span><h3>{title || "Untitled artifact"}</h3><p>{app || "Unknown source"} · {timestamp ? new Date(timestamp).toLocaleString() : "No timestamp"}</p></div>{citationId && <span className="citation-id">ID {citationId.slice(0, 8)}</span>}</header><p className="evidence-text">{text.slice(0, 500) || "No text content available."}</p>{entities.length > 0 && <div className="entity-row">{entities.map((e) => <span key={`${e.entity_type}-${e.value}`} className="entity-tag">{e.entity_type}: {e.value}</span>)}</div>}</article>; }
